version: '3'

services:
  fleetman-queue:
    image: richardchesterwood/k8s-fleetman-queue:release1
    ports:
      - '8161:8161'
    networks:
      - fleetman-private-network
    environment:
      - SPRING_PROFILES_ACTIVE=local-microservice

  fleetman-webapp:
    image: richardchesterwood/k8s-fleetman-webapp-angular:release1
    ports:
      - '80:80'
    networks:
      - fleetman-private-network
    environment:
      - SPRING_PROFILES_ACTIVE=local-microservice

  fleetman-api-gateway:
    image: richardchesterwood/k8s-fleetman-api-gateway:release1
    ports:
      - '8080:8080'
    networks:
      - fleetman-private-network
    environment:
      - SPRING_PROFILES_ACTIVE=local-microservice

  fleetman-position-simulator:
    image: richardchesterwood/k8s-fleetman-position-simulator:release1
    networks:
      - fleetman-private-network
    environment:
      - SPRING_PROFILES_ACTIVE=local-microservice

  fleetman-position-tracker:
    image: richardchesterwood/k8s-fleetman-position-tracker:release1
    networks:
      - fleetman-private-network
    environment:
      - SPRING_PROFILES_ACTIVE=local-microservice

networks:
   fleetman-private-network:
