apiVersion: monitoring.coreos.com/v1alpha1   
kind: ServiceMonitor
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      monitor: "on"
#  endpoints:
#  - port: web            # works for different port numbers as long as the name matches
#    interval: 10s        # scrape the endpoint every 10 seconds
