kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: console
    port: 8161
  - name: endpoint
    port: 61616
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: tracker
  ports:
  - name: http
    port: 8080
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: mongoport
    port: 27017
  type: ClusterIP
