apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue-replicaset
  labels:
    app: queue
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: fleetman-queue
        image: richardchesterwood/k8s-fleetman-queue
        ports:
        - containerPort: 8161
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simulator-replicaset
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
       labels:
         app: simulator
    spec:
      containers:
      - name: fleetman-position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tracker-replicaset
  labels:
    app: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
      - name: fleetman-position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker
 
